import React, { createContext, useContext, useState } from 'react';
import type { Language, Translations } from '../types/language';

export const translations: Record<Language, Translations> = {
  te: {
    appName: "హాస్టల్ OS",
    appTagline: "హైదరాబాద్ హాస్టళ్ల కోసం సులభమైన సాఫ్ట్‌వేర్",
    ownerOS: "ఓనర్ డాష్‌బోర్డ్",
    studentPortal: "స్టూడెంట్ పోర్టల్",
    morningCallList: "ఉదయం 8:00 కాల్ లిస్ట్",
    bedMatrix: "బెడ్ రూమ్ బోర్డు",
    dueToday: "ఈరోజు కట్టాల్సినవి",
    overdue: "గడువు దాటినవి",
    upcoming: "రాబోయేవి",
    allPaid: "అంతా క్లియర్",
    vacantBed: "ఖాళీ బెడ్",
    occupiedBed: "మనుషులున్నారు",
    callStudent: "కాల్ చేయండి",
    sendWhatsApp: "వాట్సాప్ రిమైండర్",
    cashReceived: "చేతికి నగదు వచ్చింది",
    securityDeposit: "సెక్యూరిటీ డిపాజిట్",
    urjaviMeter: "ఉర్జవి కరెంట్ మీటర్",
    studentOnboarding: "60-సెకన్ల విద్యార్థి అడ్మిషన్",
    saveStudent: "విద్యార్థిని చేర్చండి",
    vacateBed: "రూమ్ ఖాళీ చేయండి",
    settleDeposit: "డిపాజిట్ సెటిల్మెంట్ & రీఫండ్",
    agreedRent: "మాట్లాడుకున్న రెంట్",
    baseRent: "రూమ్ అసలు రెంట్",
    discountOffered: "రెంట్ తగ్గించాం",
    cyberabadPoliceVerification: "సైబరాబాద్ పోలీస్ వెరిఫికేషన్ (HawkEye)",
    rechargeRent: "రెంట్ కట్టండి (UPI)",
    downloadReceipt: "రసీదు డౌన్‌లోడ్",
    addHostel: "+ కొత్త హాస్టల్ జోడించండి",
    filterByFloor: "ఫ్లోర్ వారీగా",
    allBeds: "అన్ని బెడ్స్",
    studentName: "విద్యార్థి పేరు",
    phoneNumber: "ఫోన్ నంబర్",
    joiningDate: "చేరిన తేదీ",
    anchorDueDay: "ప్రతినెల కట్టాల్సిన తేదీ",
    depositStatus: "డిపాజిట్ స్థితి",
    paidCash: "నగదు ఇచ్చారు",
    paidUpi: "UPI ద్వారా కట్టారు",
    pending: "ఇంకా ఇవ్వలేదు",
    aadhaarCard: "ఆధార్ కార్డ్ ఫోటో",
    cameraSnap: "ఫోటో తీయండి",
    uploadPhoto: "అప్‌లోడ్ చేయండి",
    maintenanceDeduction: "మెయింటెనెన్స్ / పెయింటింగ్ ఖర్చు",
    netRefundAmount: "స్టూడెంట్‌కు వాపస్ ఇవ్వాల్సిన మొత్తం",
    rechargeUrjavi: "ఉర్జవి రీఛార్జ్ చేయండి",
    unitsLeft: "కరెంట్ యూనిట్లు మిగిలాయి",
    lowBalanceWarning: "కరెంట్ బ్యాలెన్స్ తక్కువగా ఉంది! రీఛార్జ్ చేయించండి.",
    emergencyContact: "తల్లిదండ్రుల / అత్యవసర ఫోన్ నంబర్",
    soundboxReceived: "డబ్బులు విజయవంతంగా జమ అయ్యాయి!",

    custom: "కస్టమ్",
    customDeposit: "ఇతర మొత్తం",
    frontSide: "ముందు భాగం",
    backSide: "వెనుక భాగం",
    sampleData: "నమూనా డేటా",
    quickChips: "త్వరిత చిప్స్",
    doubleSharing: "డబుల్ షేరింగ్",
    tripleSharing: "ట్రిపుల్ షేరింగ్",
    singleRoom: "సింగిల్ రూమ్",
    fourSharing: "ఫోర్ షేరింగ్",
    loginStudent: "స్టూడెంట్ మొబైల్ లాగిన్",
    enterMobile: "10 అంకెల మొబైల్ నంబర్",
    verifyOtp: "OTP ధృవీకరించండి",
    dateSimulator: "క్యాలెండర్ సిమ్యులేటర్",
    prevDay: "మునుపటి రోజు",
    nextDay: "మరుసటి రోజు",
    today: "ఈరోజు",
    settleAndVacate: "బెడ్ ఖాళీ చేసి రీఫండ్ చేయండి",
    unpaidDues: "పెండింగ్ అద్దె బాకీలు",
    floor: "ఫ్లోర్",
    readyForAdmission: "అడ్మిషన్లకు సిద్ధం",
    occupancy: "ఆక్యుపెన్సీ",
    daysLate: "రోజులు ఆలస్యం",
    dueTodayTag: "ఈరోజే కట్టాలి",
    paidTag: "చెల్లించారు",

    settings: "సెట్టింగ్స్ & ప్రాధాన్యతలు",
    settingsSubtitle: "భాష, సౌండ్‌బాక్స్, బ్రాంచ్ వివరాలు మరియు ప్రాధాన్యతలను మార్చుకోండి",
    languageSelect: "సిస్టమ్ భాషను ఎంచుకోండి",
    englishLang: "English (ఆంగ్లం)",
    teluguLang: "తెలుగు (సహజమైన భాష)",
    hindiLang: "हिंदी (హిందీ)",
    languageActiveNote: "తెలుగు ఎంపిక చేయబడింది. అన్ని స్క్రీన్‌లు, బటన్లు, రసీదులు మరియు రిమైండర్లు సహజమైన తెలుగులో ప్రదర్శించబడతాయి.",
    soundboxPreferences: "సౌండ్‌బాక్స్ వాయిస్ & ఆడియో",
    soundboxStatus: "కనెక్ట్ అయింది (సైబరాబాద్ నెట్‌వర్క్)",
    testSoundboxBtn: "సౌండ్‌బాక్స్ వాయిస్ టెస్ట్ చేయండి",
    activeBranchInfo: "ప్రస్తుత హాస్టల్ బ్రాంచ్ వివరాలు",
    systemCompliance: "సిస్టమ్ నిబంధనలు & అనుసంధానాలు",
    appVersionLabel: "వెర్షన్",
    close: "మూసివేయి",

    totalBedsCard: "మొత్తం బెడ్స్",
    vacantBedsCard: "ఖాళీ బెడ్స్",
    pendingDuesCard: "వసూలు చేయాల్సినవి",
    collectedRentCard: "వచ్చిన అద్దె",
    bedsLabel: "బెడ్స్",
    locationCyberabad: "హైదరాబాద్ (సైబరాబాద్)",
    vacantCountText: "ఖాళీ",
    occupiedCountText: "ఉన్నారు",
    yourBranches: "మీ హాస్టల్ బ్రాంచ్‌లు",
    addBranch: "కొత్త హాస్టల్ జోడించండి",
    newHostel: "+ కొత్త హాస్టల్",
    resetDate: "20 సెప్టెంబర్ 2026కి రీసెట్ చేయండి",

    callListSubtitle: "స్టూడెంట్స్ అద్దె వసూలు లిస్ట్ — 1-ట్యాప్ కాల్, వాట్సాప్ మరియు సౌండ్‌బాక్స్ రికార్డ్",
    overdueSubtext: "గడువు దాటింది",
    dueTodaySubtext: "ఈరోజే వసూలు చేయాలి",
    upcomingSubtext: "రాబోయే 3 రోజుల్లో",
    paidSubtext: "చెల్లించినవి",
    emptyPaidList: "ఈ కేటగిరీలో రికార్డులు లేవు.",
    emptyDuesList: "ఈ లిస్ట్‌లో ఎవరూ లేరు! అన్నీ క్లియర్ అయ్యాయి.",
    room: "రూమ్",
    bed: "బెడ్",
    dueCycleDay: "చేరిన రోజు: తేదీ",
    rentDiscount: "రెంట్ తగ్గింపు",
    deposit: "డిపాజిట్",
    paid: "ఇచ్చారు",
    paidDate: "చెల్లించిన తేదీ",
    soundboxConfirmed: "సౌండ్‌బాక్స్ కన్ఫర్మ్ అయింది ✓",
    monthSuffix: "/నెల",
    rechargeUrgent: "రీఛార్జ్ చేయాలి!",
    onboardBed: "1-ట్యాప్ అడ్మిషన్",

    activeStudent: "యాక్టివ్ విద్యార్థి",
    call: "కాల్ చేయండి",
    whatsAppMsg: "వాట్సాప్ సందేశం",
    monthlyCycle: "ప్రతినెల సైకిల్",
    everyDay: "ప్రతి",
    dayDate: "వ తేదీ",
    stickerDiscount: "స్టిక్కర్ రెంట్ నుండి తగ్గింపు",
    save: "సేవ్",
    cancel: "రద్దు",
    edit: "మార్చండి",
    urjaviConnected: "Urjavi యాప్ అనుసంధానం",
    collegeCompany: "కళాశాల / కంపెనీ:",
    hometown: "స్వస్థలం:",
    bloodGroup: "బ్లడ్ గ్రూప్:",
    aadhaarPhotos: "ఆధార్ కార్డు ఫోటోలు",
    studentPortalLogin: "స్టూడెంట్ పోర్టల్ లాగిన్",
    vacateSuccess: "బెడ్ విజయవంతంగా ఖాళీ చేయబడింది!",
    vacateSuccessSub: "డిపాజిట్ సెటిల్మెంట్ పూర్తయింది. బెడ్ ఇప్పుడు ఖాళీగా మారింది.",
    netRefundSub: "విద్యార్థికి తిరిగి చెల్లించాల్సిన నికర మొత్తం",
    vacateReason: "కారణం / గమనిక:",
    vacateReasonPlaceholder: "ఉదా: ఉద్యోగ మార్పిడి / కోర్సు పూర్తయింది",
    policeSheetSubtitle: "తెలంగాణ పోలీస్ టెనెంట్ వెరిఫికేషన్ షీట్",
    printPdf: "ప్రింట్ / PDF సేవ్ చేయండి",
    addHostelSubtitle: "2 నిమిషాల్లో కొత్త ప్రాపర్టీ సెటప్ చేయండి",
    quickAreas: "త్వరిత ప్రాంతాలు:",
    hostelNameLabel: "హాస్టల్ పేరు *",
    addressLabel: "హైదరాబాద్ చిరునామా",
    totalFloorsLabel: "మొత్తం ఫ్లోర్లు:",
    roomsPerFloorLabel: "ఒక్కో ఫ్లోర్‌కు రూములు:",
    sharingLabel: "రూమ్ షేరింగ్:",
    baseRentLabel: "నెలవారీ రెంట్:",
    ownerPhoneLabel: "ఓనర్ ఫోన్:",
    createBranchBtn: "హాస్టల్ బ్రాంచ్‌ను సేవ్ చేయండి",
    autoGenNotice: "రూములు మరియు బెడ్స్ ఆటోమేటిక్‌గా ఉర్జవి మీటర్ IDలతో సృష్టించబడతాయి!",

    noAppRequired: "యాప్ డౌన్‌లోడ్ అవసరం లేదు • తక్షణ మొబైల్ లాగిన్",
    getOtp: "OTP పంపండి",
    demoStudentSelect: "డెమో కోసం 1-ట్యాప్ విద్యార్థి ఎంపిక:",
    otpVerification: "OTP ధృవీకరణ",
    otpSentTo: "+91 నంబర్‌కు OTP పంపాము",
    demoOtpNotice: "(డెమో OTP: 4826)",
    changeMobile: "మొబైల్ నంబర్ మార్చండి",
    goToOwner: "ఓనర్ OS డాష్‌బోర్డ్‌కి వెళ్లండి",
    noStudentsInHostel: "ఈ హాస్టల్‌లో విద్యార్థుల రికార్డులు లేవు",
    noStudentsSub: "ఓనర్ డాష్‌బోర్డ్‌లో ఖాళీ బెడ్ పై ట్యాప్ చేసి మొదటి విద్యార్థిని చేర్చండి.",
    loginLabel: "లాగిన్:",
    switchLabel: "మారండి",
    ownerView: "ఓనర్ వ్యూ",
    verifiedInmate: "ధృవీకరించబడిన విద్యార్థి",
    meterIdLabel: "మీటర్ ID:",
    rechargeUrjaviBtn: "ఉర్జవి మీటర్ రీఛార్జ్ చేయండి (+యూనిట్లు)",
    rentStatus: "రెంట్ స్థితి",
    allPaidStatus: "✓ అంతా క్లియర్ (బాకీలు లేవు)",
    dueDateLabel: "గడువు తేదీ:",
    rentPaidNote: "ఈ నెలకు రెంట్ చెల్లించబడింది.",
    basePriceLabel: "రూమ్ అసలు ధర:",
    ownerDiscountLabel: "ఓనర్ ఇచ్చిన తగ్గింపు:",
    depositRecordLabel: "సెక్యూరిటీ డిపాజిట్ రికార్డ్:",
    depositReceived: "జమ అయింది",
    payRentBtn: "రెంట్ కట్టండి (PhonePe / GPay)",
    noDuesPending: "✓ మీ వద్ద ఎలాంటి పెండింగ్ అద్దె బకాయిలు లేవు. ధన్యవాదాలు!",
    digitalReceipts: "డిజిటల్ రసీదులు",
    records: "రికార్డులు",
    noReceipts: "ఇంకా ఎలాంటి రసీదులు లేవు.",
    receiptBtn: "రసీదు",
    kycVerifiedBanner: "మీ ఆధార్ KYC ధృవీకరణ పూర్తయింది. సురక్షిత డిజిటల్ రికార్డ్.",

    officialReceipt: "అధికారిక డిజిటల్ రసీదు",
    receiptNo: "రసీదు సంఖ్య:",
    dateTime: "తేదీ & సమయం:",
    allocatedSpace: "కేటాయించిన రూమ్ & బెడ్:",
    particulars: "వివరణ:",
    paymentMode: "చెల్లింపు విధానం:",
    amountPaid: "చెల్లించిన మొత్తం",
    noDuesCycle: "(ఈ నెలకు ఎలాంటి బాకీలు లేవు)",
    qrVerify: "చెల్లింపు ప్రామాణికతను ధృవీకరించడానికి స్కాన్ చేయండి.",
    authorizedSign: "అధికారిక సంతకం",
    paymentSuccess: "చెల్లింపు విజయవంతమైంది!",
    soundboxSuccessMsg: "PhonePe సౌండ్‌బాక్స్‌లో చెల్లింపు విజయవంతంగా రికార్డ్ అయింది!",
    loadingReceipt: "రసీదు లోడ్ అవుతోంది...",
    selectUpiApp: "UPI యాప్ ఎంచుకోండి:",
    showQr: "QR కోడ్ స్కాన్",
    showApps: "యాప్‌లు చూపించు",
    processingUpi: "UPI ప్రాసెసింగ్ అవుతోంది...",
    completeUpi: "UPI ద్వారా చెల్లించండి",
    rechargeSuccess: "ఉర్జవి మీటర్ రీఛార్జ్ విజయవంతమైంది!",
    unitsAddedNotice: "యూనిట్లు మీటర్‌కు యాడ్ చేయబడ్డాయి.",
    currentBalance: "ప్రస్తుత బ్యాలెన్స్:",
    selectRechargeAmount: "రీఛార్జ్ మొత్తం ఎంచుకోండి:",
    useQuickChips: "త్వరిత చిప్స్ ఉపయోగించండి",
    customAmountBtn: "+ ఇతర మొత్తం",
    urjaviAppNote: "గమనిక: విద్యార్థులు వారి స్వంత Urjavi యాప్ ద్వారా లేదా నేరుగా ఇక్కడి నుండి విద్యుత్ మీటర్ రీఛార్జ్ చేసుకోవచ్చు (సుమారు ₹7/యూనిట్).",
    rechargeBtn: "రీఛార్జ్ చేయండి",
    upload: "అప్‌లోడ్",
    camera: "కెమెరా",
    standard: "సాధారణ",
    appFooterTagline: "ఉర్జవి స్మార్ట్ మీటర్, ₹5,000 సెక్యూరిటీ డిపాజిట్ మరియు సైబరాబాద్ పోలీస్ HawkEye రికార్డులతో ప్రత్యేకంగా రూపొందించబడింది.",
    pleaseEnterName: "దయచేసి విద్యార్థి పేరు నమోదు చేయండి",
    pleaseEnterPhone: "దయచేసి సరైన 10 అంకెల మొబైల్ నంబర్ నమోదు చేయండి",
    pleaseEnterHostelName: "దయచేసి హాస్టల్ పేరు నమోదు చేయండి",
    invalidOtp: "తప్పుడు OTP. డెమో కోసం 4826 ఉపయోగించండి.",
    studentNotFound: "ఈ మొబైల్ నంబర్‌తో విద్యార్థి రికార్డు కనపడలేదు.",

    // Granular Professional UI & System Keys
    active: "యాక్టివ్",
    policeStationLabel: "పోలీస్ స్టేషన్",
    inventory: "ఇన్వెంటరీ",
    roomsCount: "రూములు",
    verificationPortal: "అధికారిక ధృవీకరణ పోర్టల్",
    iotGateway: "ప్రీపెయిడ్ విద్యుత్ IoT గేట్‌వే",
    pwaReady: "PWA సిద్ధంగా ఉంది",
    units: "యూనిట్లు",
    amountLabel: "మొత్తం",
    phoneLabel: "ఫోన్",
    recommended: "సిఫార్సు చేయబడింది",
    instantTransfer: "బ్యాంక్ నుండి బ్యాంక్ తక్షణ బదిలీ",
    zeroFeeCheckout: "ఎటువంటి ఛార్జీలు లేని వేగవంతమైన చెల్లింపు",
    sslEncrypted: "256-బిట్ SSL భద్రత • రేజర్‌పే సర్టిఫైడ్ చెల్లింపు",
    scanAnyUpi: "ఏదైనా UPI యాప్ ద్వారా స్కాన్ చేయండి (PhonePe / GPay / Paytm)",
    secureUpi: "100% సురక్షితమైన UPI",
    qrVerificationTitle: "హాస్టల్ OS QR ధృవీకరణ",
    digitallyVerifiedReceipt: "డిజిటల్‌గా ధృవీకరించబడిన చెల్లింపు రసీదు",
    enterDepositPlaceholder: "డిపాజిట్ మొత్తాన్ని నమోదు చేయండి",
    enterAmountPlaceholder: "మొత్తాన్ని నమోదు చేయండి",
    hawkEyeVerifiedRecord: "సైబరాబాద్ పోలీస్ HawkEye ధృవీకరించిన రికార్డు",

    // Payment Methods
    methodCash: "నగదు",
    methodUpi: "UPI",
    methodSoundbox: "సౌండ్‌బాక్స్"
  },
  hi: {
    appName: "हॉस्टल OS",
    appTagline: "हैदराबाद हॉस्टल्स के लिए सरल ऑपरेटिंग सिस्टम",
    ownerOS: "मालिक डैशबोर्ड",
    studentPortal: "छात्र पोर्टल",
    morningCallList: "सुबह 8:00 बजे की कॉल लिस्ट",
    bedMatrix: "बेड एवं रूम बोर्ड",
    dueToday: "आज देय किराया",
    overdue: "अतिदेय",
    upcoming: "आगामी देय",
    allPaid: "सब चुकता",
    vacantBed: "खाली बेड",
    occupiedBed: "भरा हुआ बेड",
    callStudent: "कॉल करें",
    sendWhatsApp: "व्हाट्सएप लिंक भेजें",
    cashReceived: "कैश प्राप्त हुआ",
    securityDeposit: "सिक्योरिटी डिपॉजिट",
    urjaviMeter: "उर्जवी बिजली मीटर",
    studentOnboarding: "60-सेकंड छात्र प्रवेश",
    saveStudent: "छात्र को जोड़ें",
    vacateBed: "कमरा खाली करें",
    settleDeposit: "डिपॉजिट सेटलमेंट एवं रिफंड",
    agreedRent: "तय किराया",
    baseRent: "कमरे का मूल किराया",
    discountOffered: "छूट दी गई",
    cyberabadPoliceVerification: "साइबराबाद पुलिस सत्यापन (HawkEye)",
    rechargeRent: "किराया भरें (UPI)",
    downloadReceipt: "रसीद डाउनलोड करें",
    addHostel: "+ नया हॉस्टल जोड़ें",
    filterByFloor: "मंजिल अनुसार",
    allBeds: "सभी बेड",
    studentName: "छात्र का नाम",
    phoneNumber: "मोबाइल नंबर",
    joiningDate: "शामिल होने की तिथि",
    anchorDueDay: "मासिक देय तिथि",
    depositStatus: "डिपॉजिट स्थिति",
    paidCash: "नकद प्राप्त",
    paidUpi: "UPI द्वारा प्राप्त",
    pending: "बाकी है",
    aadhaarCard: "आधार कार्ड फोटो",
    cameraSnap: "फोटो खींचें",
    uploadPhoto: "अपलोड करें",
    maintenanceDeduction: "मेंटेनेंस / पुताई कटौती",
    netRefundAmount: "छात्र को वापसी योग्य राशि",
    rechargeUrjavi: "उर्जवी रीचार्ज करें",
    unitsLeft: "बिजली यूनिट बची हैं",
    lowBalanceWarning: "बिजली बैलेंस कम है! तुरंत रीचार्ज करें।",
    emergencyContact: "अभिभावक / आपातकालीन नंबर",
    soundboxReceived: "पैसे सफलतापूर्वक प्राप्त हुए!",

    custom: "कस्टम",
    customDeposit: "अन्य राशि",
    frontSide: "सामने का भाग",
    backSide: "पीछे का भाग",
    sampleData: "नमूना डेटा",
    quickChips: "त्वरित चिप्स",
    doubleSharing: "डबल शेयरिंग",
    tripleSharing: "ट्रिपल शेयरिंग",
    singleRoom: "सिंगल रूम",
    fourSharing: "चार शेयरिंग",
    loginStudent: "छात्र मोबाइल लॉगिन",
    enterMobile: "10 अंकों का मोबाइल नंबर",
    verifyOtp: "OTP सत्यापित करें",
    dateSimulator: "कैलेंडर सिम्युलेटर",
    prevDay: "पिछला दिन",
    nextDay: "अगला दिन",
    today: "आज",
    settleAndVacate: "खाली कर रिफंड करें",
    unpaidDues: "बकाया किराया",
    floor: "मंजिल",
    readyForAdmission: "प्रवेश हेतु तैयार",
    occupancy: "ऑक्यूपेंसी",
    daysLate: "दिन देर",
    dueTodayTag: "आज देय",
    paidTag: "चुकता",

    settings: "सेटिंग्स और प्राथमिकताएं",
    settingsSubtitle: "भाषा, साउंडबॉक्स और ऐप प्राथमिकताएं कॉन्फ़िगर करें",
    languageSelect: "सिस्टम भाषा चुनें",
    englishLang: "English (अंग्रेज़ी)",
    teluguLang: "తెలుగు (तेलुगु)",
    hindiLang: "हिंदी (सरल हिंदी)",
    languageActiveNote: "हिंदी चुनी गई। सभी स्क्रीन, बटन, रसीदें और संदेश शुद्ध हिंदी में प्रदर्शित होंगे।",
    soundboxPreferences: "साउंडबॉक्स आवाज़ एवं ऑडियो",
    soundboxStatus: "सक्रिय एवं कनेक्टेड (साइबराबाद मेश)",
    testSoundboxBtn: "साउंडबॉक्स घोषणा का परीक्षण करें",
    activeBranchInfo: "सक्रिय शाखा विवरण",
    systemCompliance: "सिस्टम अनुपालन एवं एकीकरण",
    appVersionLabel: "संस्करण",
    close: "बंद करें",

    totalBedsCard: "कुल बेड",
    vacantBedsCard: "खाली बेड",
    pendingDuesCard: "बकाया राशि",
    collectedRentCard: "प्राप्त किराया",
    bedsLabel: "बेड",
    locationCyberabad: "साइबराबाद, हैदराबाद",
    vacantCountText: "खाली",
    occupiedCountText: "भरे हुए",
    yourBranches: "आपकी हॉस्टल शाखाएं",
    addBranch: "नई हॉस्टल शाखा जोड़ें",
    newHostel: "+ नया हॉस्टल",
    resetDate: "20 सितम्बर 2026 पर रीसेट करें",

    callListSubtitle: "छात्र किराया वसूली सूची — 1-टैप कॉल, व्हाट्सएप एवं साउंडबॉक्स रिकॉर्ड",
    overdueSubtext: "समय सीमा पार",
    dueTodaySubtext: "आज ही वसूलें",
    upcomingSubtext: "अगले 3 दिनों में",
    paidSubtext: "प्राप्त हो गया",
    emptyPaidList: "इस श्रेणी में कोई रिकॉर्ड नहीं है।",
    emptyDuesList: "इस सूची में कोई बकाया नहीं है! सब चुकता।",
    room: "कमरा",
    bed: "बेड",
    dueCycleDay: "देय चक्र: तारीख",
    rentDiscount: "किराया छूट",
    deposit: "डिपॉजिट",
    paid: "प्राप्त",
    paidDate: "भुगतान तिथि",
    soundboxConfirmed: "साउंडबॉक्स द्वारा सत्यापित ✓",
    monthSuffix: "/माह",
    rechargeUrgent: "रीचार्ज आवश्यक!",
    onboardBed: "1-टैप प्रवेश",

    activeStudent: "सक्रिय छात्र",
    call: "कॉल करें",
    whatsAppMsg: "व्हाट्सएप संदेश",
    monthlyCycle: "मासिक देय चक्र",
    everyDay: "हर महीने",
    dayDate: "तारीख",
    stickerDiscount: "मूल किराये से छूट",
    save: "सहेजें",
    cancel: "रद्द करें",
    edit: "संपादित करें",
    urjaviConnected: "उर्जवी ऐप कनेक्टेड",
    collegeCompany: "कॉलेज / कंपनी:",
    hometown: "मूल स्थान:",
    bloodGroup: "रक्त समूह:",
    aadhaarPhotos: "आधार कार्ड फोटो",
    studentPortalLogin: "छात्र पोर्टल लॉगिन",
    vacateSuccess: "बेड सफलतापूर्वक खाली कर दिया गया!",
    vacateSuccessSub: "डिपॉजिट सेटलमेंट पूरा हुआ। बेड अब खाली है।",
    netRefundSub: "छात्र को वापस की जाने वाली शुद्ध राशि",
    vacateReason: "कारण / विवरण:",
    vacateReasonPlaceholder: "उदा: नौकरी स्थानांतरण / कोर्स पूरा हुआ",
    policeSheetSubtitle: "तेलंगाना पुलिस किरायेदार सत्यापन शीट",
    printPdf: "प्रिंट / पीडीएफ सहेजें",
    addHostelSubtitle: "2 मिनट में नई प्रॉपर्टी सेटअप करें",
    quickAreas: "त्वरित क्षेत्र टेम्पलेट्स:",
    hostelNameLabel: "हॉस्टल का नाम *",
    addressLabel: "हैदराबाद का पता",
    totalFloorsLabel: "कुल मंजिलें:",
    roomsPerFloorLabel: "प्रति मंजिल कमरे:",
    sharingLabel: "डिफ़ॉल्ट शेयरिंग:",
    baseRentLabel: "मूल किराया:",
    ownerPhoneLabel: "मालिक का फोन:",
    createBranchBtn: "हॉस्टल शाखा बनाएं",
    autoGenNotice: "कमरे और बेड उर्जवी मीटर आईडी के साथ स्वतः बन जाएंगे!",

    noAppRequired: "ऐप डाउनलोड की आवश्यकता नहीं • त्वरित मोबाइल लॉगिन",
    getOtp: "OTP प्राप्त करें",
    demoStudentSelect: "डेमो के लिए 1-टैप छात्र चुनें:",
    otpVerification: "OTP सत्यापन",
    otpSentTo: "+91 पर OTP भेजा गया",
    demoOtpNotice: "(डेमो OTP: 4826)",
    changeMobile: "मोबाइल नंबर बदलें",
    goToOwner: "मालिक डैशबोर्ड पर जाएं",
    noStudentsInHostel: "इस हॉस्टल में कोई छात्र रिकॉर्ड नहीं है",
    noStudentsSub: "मालिक डैशबोर्ड पर खाली बेड चुनकर पहले छात्र को जोड़ें।",
    loginLabel: "लॉगिन:",
    switchLabel: "बदलें",
    ownerView: "मालिक व्यू",
    verifiedInmate: "सत्यापित छात्र",
    meterIdLabel: "मीटर आईडी:",
    rechargeUrjaviBtn: "उर्जवी मीटर रीचार्ज करें (+यूनिट)",
    rentStatus: "किराया स्थिति",
    allPaidStatus: "✓ सब चुकता (कोई बकाया नहीं)",
    dueDateLabel: "देय तिथि:",
    rentPaidNote: "इस माह का किराया चुकता हो चुका है।",
    basePriceLabel: "कमरे का मूल किराया:",
    ownerDiscountLabel: "दी गई छूट:",
    depositRecordLabel: "डिपॉजिट रिकॉर्ड:",
    depositReceived: "जमा हुआ",
    payRentBtn: "किराया भरें (PhonePe / GPay)",
    noDuesPending: "✓ आपका कोई बकाया किराया नहीं है। धन्यवाद!",
    digitalReceipts: "डिजिटल रसीदें",
    records: "रिकॉर्ड",
    noReceipts: "अभी कोई रसीद नहीं है।",
    receiptBtn: "रसीद",
    kycVerifiedBanner: "आपका आधार केवाईसी सत्यापित है। सुरक्षित डिजिटल रिकॉर्ड।",

    officialReceipt: "आधिकारिक डिजिटल रसीद",
    receiptNo: "रसीद संख्या:",
    dateTime: "तिथि एवं समय:",
    allocatedSpace: "आवंटित कमरा और बेड:",
    particulars: "विवरण:",
    paymentMode: "भुगतान माध्यम:",
    amountPaid: "भुगतान राशि",
    noDuesCycle: "(इस चक्र के लिए कोई बकाया नहीं)",
    qrVerify: "डिजिटल भुगतान सत्यापन के लिए स्कैन करें।",
    authorizedSign: "अधिकृत हस्ताक्षर",
    paymentSuccess: "भुगतान सफल रहा!",
    soundboxSuccessMsg: "फोनपे साउंडबॉक्स पर भुगतान सफलतापूर्वक दर्ज हुआ!",
    loadingReceipt: "रसीद लोड हो रही है...",
    selectUpiApp: "UPI ऐप चुनें:",
    showQr: "क्यूआर कोड स्कैन",
    showApps: "ऐप्स दिखाएं",
    processingUpi: "यूपीआई भुगतान संसाधित हो रहा है...",
    completeUpi: "यूपीआई से भुगतान करें",
    rechargeSuccess: "उर्जवी मीटर सफलतापूर्वक रीचार्ज हुआ!",
    unitsAddedNotice: "यूनिट कमरे के मीटर में जुड़ गई हैं।",
    currentBalance: "वर्तमान बैलेंस:",
    selectRechargeAmount: "रीचार्ज राशि चुनें:",
    useQuickChips: "त्वरित चिप्स का उपयोग करें",
    customAmountBtn: "+ अन्य राशि",
    urjaviAppNote: "नोट: छात्र सीधे यहां से या आधिकारिक उर्जवी ऐप से बिजली रीचार्ज कर सकते हैं (~₹7/यूनिट)।",
    rechargeBtn: "रीचार्ज करें",
    upload: "अपलोड",
    camera: "कैमरा",
    standard: "मानक",
    appFooterTagline: "उर्जवी स्मार्ट मीटर, ₹5,000 सिक्योरिटी डिपॉजिट एवं साइबराबाद पुलिस HawkEye सत्यापन के साथ निर्मित।",
    pleaseEnterName: "कृपया छात्र का नाम दर्ज करें",
    pleaseEnterPhone: "कृपया 10 अंकों का मान्य मोबाइल नंबर दर्ज करें",
    pleaseEnterHostelName: "कृपया हॉस्टल का नाम दर्ज करें",
    invalidOtp: "अमान्य OTP. डेमो के लिए 4826 का उपयोग करें।",
    studentNotFound: "इस मोबाइल नंबर से कोई छात्र रिकॉर्ड नहीं मिला।",

    // Granular Professional UI & System Keys
    active: "सक्रिय",
    policeStationLabel: "पुलिस स्टेशन",
    inventory: "इन्वेंटरी",
    roomsCount: "कमरे",
    verificationPortal: "अनुपालित सत्यापन पोर्टल",
    iotGateway: "प्रीपेड बिजली IoT गेटवे",
    pwaReady: "PWA तैयार",
    units: "यूनिट",
    amountLabel: "राशि",
    phoneLabel: "फोन",
    recommended: "अनुशंसित",
    instantTransfer: "तत्काल बैंक-से-बैंक ट्रांसफर",
    zeroFeeCheckout: "तेज़ एवं शून्य-शुल्क भुगतान",
    sslEncrypted: "256-बिट SSL सुरक्षित • रेज़रपे प्रमाणित भुगतान",
    scanAnyUpi: "किसी भी UPI ऐप से स्कैन करें (PhonePe / GPay / Paytm)",
    secureUpi: "100% सुरक्षित UPI",
    qrVerificationTitle: "हॉस्टल OS QR सत्यापन",
    digitallyVerifiedReceipt: "डिजिटल रूप से सत्यापित भुगतान रसीद",
    enterDepositPlaceholder: "डिपॉजिट राशि दर्ज करें",
    enterAmountPlaceholder: "राशि दर्ज करें",
    hawkEyeVerifiedRecord: "साइबराबाद पुलिस HawkEye सत्यापित रिकॉर्ड",

    // Payment Methods
    methodCash: "नकद",
    methodUpi: "UPI",
    methodSoundbox: "साउंडबॉक्स"
  },
  en: {
    appName: "Hostel OS",
    appTagline: "Zero-friction Hyderabad Hostel Operating System",
    ownerOS: "Owner Dashboard",
    studentPortal: "Student Portal",
    morningCallList: "8:00 AM Morning Action Call List",
    bedMatrix: "Interactive Bed Board",
    dueToday: "Due Today",
    overdue: "Overdue",
    upcoming: "Upcoming",
    allPaid: "All Clear",
    vacantBed: "Vacant Bed",
    occupiedBed: "Occupied",
    callStudent: "Call Now",
    sendWhatsApp: "WhatsApp Reminder",
    cashReceived: "Cash Received",
    securityDeposit: "Security Deposit",
    urjaviMeter: "Urjavi Electricity Meter",
    studentOnboarding: "60-Second Student Onboarding",
    saveStudent: "Save & Allocate Bed",
    vacateBed: "Vacate Bed & Settle Deposit",
    settleDeposit: "Deposit Settlement Calculator",
    agreedRent: "Agreed Negotiated Rent",
    baseRent: "Base Rent",
    discountOffered: "Discount Given",
    cyberabadPoliceVerification: "Cyberabad Police Verification (HawkEye)",
    rechargeRent: "Recharge Rent (UPI)",
    downloadReceipt: "Download Receipt",
    addHostel: "+ Add New Hostel",
    filterByFloor: "Filter by Floor",
    allBeds: "All Beds",
    studentName: "Student Name",
    phoneNumber: "Phone Number",
    joiningDate: "Joining Date",
    anchorDueDay: "Monthly Due Day",
    depositStatus: "Deposit Status",
    paidCash: "Paid via Cash",
    paidUpi: "Paid via UPI",
    pending: "Pending",
    aadhaarCard: "Aadhaar Card Photo",
    cameraSnap: "Snap Photo",
    uploadPhoto: "Upload Photo",
    maintenanceDeduction: "Maintenance Deduction",
    netRefundAmount: "Net Student Refund",
    rechargeUrjavi: "Recharge Urjavi Meter",
    unitsLeft: "Units Remaining",
    lowBalanceWarning: "Urjavi balance low! Power will disconnect if not recharged.",
    emergencyContact: "Parent / Emergency Contact",
    soundboxReceived: "Payment received on Soundbox successfully!",

    custom: "Custom",
    customDeposit: "Custom Amount",
    frontSide: "Front Side",
    backSide: "Back Side",
    sampleData: "Auto Fill Sample",
    quickChips: "Quick Chips",
    doubleSharing: "Double Sharing",
    tripleSharing: "Triple Sharing",
    singleRoom: "Single Room",
    fourSharing: "Four Sharing",
    loginStudent: "Student Mobile Login",
    enterMobile: "Enter 10-Digit Mobile",
    verifyOtp: "Verify OTP",
    dateSimulator: "Date Simulator",
    prevDay: "Prev Day",
    nextDay: "Next Day",
    today: "Today",
    settleAndVacate: "Confirm & Vacate Bed",
    unpaidDues: "Unpaid Rent Dues",
    floor: "Floor",
    readyForAdmission: "Ready for Admission",
    occupancy: "Occupancy",
    daysLate: "Days Overdue",
    dueTodayTag: "Due Today",
    paidTag: "Paid",

    settings: "Settings & Preferences",
    settingsSubtitle: "Configure language, soundbox audio, branch details and preferences",
    languageSelect: "Select System Language",
    englishLang: "English (Clean Professional)",
    teluguLang: "Telugu (Authentic Telugu)",
    hindiLang: "Hindi (Standard)",
    languageActiveNote: "English selected. All screens, buttons, receipts, and messages will display in clean English.",
    soundboxPreferences: "Soundbox Voice & Audio",
    soundboxStatus: "Connected & Active (Cyberabad Mesh)",
    testSoundboxBtn: "Test Soundbox Chime & Voice",
    activeBranchInfo: "Active Branch Information",
    systemCompliance: "System Compliance & Integrations",
    appVersionLabel: "Version",
    close: "Close",

    totalBedsCard: "Total Beds",
    vacantBedsCard: "Vacant Beds",
    pendingDuesCard: "Pending Dues",
    collectedRentCard: "Rent Collected",
    bedsLabel: "Beds",
    locationCyberabad: "Cyberabad, Hyderabad",
    vacantCountText: "Vacant",
    occupiedCountText: "Occupied",
    yourBranches: "Your Hostel Branches",
    addBranch: "Add Hostel Branch",
    newHostel: "+ New Hostel",
    resetDate: "Reset to 20 Sep 2026",

    callListSubtitle: "Student Rent Collection List — 1-Tap Call, WhatsApp & Soundbox Record",
    overdueSubtext: "Overdue",
    dueTodaySubtext: "Collect Today",
    upcomingSubtext: "Next 3 Days",
    paidSubtext: "Paid & Cleared",
    emptyPaidList: "No records in this category.",
    emptyDuesList: "No pending dues in this list! All clear.",
    room: "Room",
    bed: "Bed",
    dueCycleDay: "Due Cycle: Day",
    rentDiscount: "Rent Discount",
    deposit: "Deposit",
    paid: "Paid",
    paidDate: "Paid Date",
    soundboxConfirmed: "Soundbox Confirmed ✓",
    monthSuffix: "/mo",
    rechargeUrgent: "Recharge Needed!",
    onboardBed: "1-Tap Onboard",

    activeStudent: "Active Tenant",
    call: "Call",
    whatsAppMsg: "WhatsApp",
    monthlyCycle: "Monthly Due Cycle",
    everyDay: "Every",
    dayDate: "th",
    stickerDiscount: "Discount from Sticker",
    save: "Save",
    cancel: "Cancel",
    edit: "Edit",
    urjaviConnected: "Urjavi App Connected",
    collegeCompany: "College / Company:",
    hometown: "Hometown:",
    bloodGroup: "Blood Group:",
    aadhaarPhotos: "Aadhaar Card Photos",
    studentPortalLogin: "Student Portal Login",
    vacateSuccess: "Bed Vacated Successfully!",
    vacateSuccessSub: "Deposit settlement complete. Bed is now vacant (Green).",
    netRefundSub: "Net amount refundable to student",
    vacateReason: "Reason / Notes:",
    vacateReasonPlaceholder: "e.g. Job change / Course completed",
    policeSheetSubtitle: "Telangana Police Tenant Verification Sheet",
    printPdf: "Print / Save PDF",
    addHostelSubtitle: "Setup new property in 2 minutes",
    quickAreas: "Quick Area Templates:",
    hostelNameLabel: "Hostel / PG Name *",
    addressLabel: "Address in Hyderabad",
    totalFloorsLabel: "Total Floors:",
    roomsPerFloorLabel: "Rooms per Floor:",
    sharingLabel: "Default Sharing:",
    baseRentLabel: "Default Rent (Base):",
    ownerPhoneLabel: "Owner Phone:",
    createBranchBtn: "Create Hostel Branch",
    autoGenNotice: "rooms and beds will be automatically generated with Urjavi Meter IDs!",

    noAppRequired: "No App Download Required • Instant Mobile Login",
    getOtp: "Get OTP",
    demoStudentSelect: "1-Tap Demo Student Selection:",
    otpVerification: "OTP Verification",
    otpSentTo: "OTP sent to +91",
    demoOtpNotice: "(Demo OTP: 4826)",
    changeMobile: "Change Mobile Number",
    goToOwner: "Go to Owner OS Dashboard",
    noStudentsInHostel: "No student records found in this hostel",
    noStudentsSub: "Tap any vacant bed on Owner Dashboard to onboard the first student.",
    loginLabel: "Login:",
    switchLabel: "Switch",
    ownerView: "Owner View",
    verifiedInmate: "Verified Inmate",
    meterIdLabel: "Meter ID:",
    rechargeUrjaviBtn: "Recharge Urjavi Meter (+Units)",
    rentStatus: "Rent Status",
    allPaidStatus: "✓ All Clear (No Dues)",
    dueDateLabel: "Due Date:",
    rentPaidNote: "Rent for this cycle is fully paid.",
    basePriceLabel: "Room Base Price:",
    ownerDiscountLabel: "Owner Discount:",
    depositRecordLabel: "Security Deposit Record:",
    depositReceived: "Paid",
    payRentBtn: "Pay Rent via UPI (PhonePe / GPay)",
    noDuesPending: "✓ You have no pending rent dues. Thank you!",
    digitalReceipts: "Digital Receipts",
    records: "Records",
    noReceipts: "No receipts available yet.",
    receiptBtn: "Receipt",
    kycVerifiedBanner: "Your Aadhaar KYC is verified. Secure digital record.",

    officialReceipt: "Official Digital Receipt",
    receiptNo: "Receipt No:",
    dateTime: "Date & Time:",
    allocatedSpace: "Allocated Bed:",
    particulars: "Particulars:",
    paymentMode: "Mode:",
    amountPaid: "Amount Paid",
    noDuesCycle: "(No dues pending for this cycle)",
    qrVerify: "Scan to verify digital payment authenticity.",
    authorizedSign: "Authorized Sign",
    paymentSuccess: "Payment Successful!",
    soundboxSuccessMsg: "Payment received successfully on PhonePe Soundbox!",
    loadingReceipt: "Loading receipt...",
    selectUpiApp: "Select UPI App:",
    showQr: "Scan QR Code",
    showApps: "Show UPI Apps",
    processingUpi: "Processing UPI Payment...",
    completeUpi: "Pay via UPI",
    rechargeSuccess: "Urjavi Meter Recharged Successfully!",
    unitsAddedNotice: "units added to room meter.",
    currentBalance: "Current Balance:",
    selectRechargeAmount: "Select Recharge Amount:",
    useQuickChips: "Use Quick Chips",
    customAmountBtn: "+ Custom Amount",
    urjaviAppNote: "Note: Students can recharge directly here or via the official Urjavi mobile app (~₹7/unit).",
    rechargeBtn: "Recharge",
    upload: "Upload",
    camera: "Camera",
    standard: "Standard",
    appFooterTagline: "Purpose-built with Urjavi Smart Meter integration, ₹5,000 security deposit lifecycle, and Cyberabad Police HawkEye verification.",
    pleaseEnterName: "Please enter student name",
    pleaseEnterPhone: "Please enter a valid 10-digit mobile number",
    pleaseEnterHostelName: "Please enter hostel name",
    invalidOtp: "Invalid OTP. Use 4826 for demo.",
    studentNotFound: "No student record found with this mobile number.",

    // Granular Professional UI & System Keys
    active: "Active",
    policeStationLabel: "Police Station",
    inventory: "Inventory",
    roomsCount: "Rooms",
    verificationPortal: "Compliant Verification Portal",
    iotGateway: "Prepaid Power IoT Gateway",
    pwaReady: "PWA Ready",
    units: "units",
    amountLabel: "Amount",
    phoneLabel: "Phone",
    recommended: "Recommended",
    instantTransfer: "Instant Bank-to-Bank Transfer",
    zeroFeeCheckout: "Fast zero-fee checkout",
    sslEncrypted: "256-bit SSL Encrypted • Razorpay Certified Payment",
    scanAnyUpi: "Scan with any UPI App (PhonePe / GPay / Paytm)",
    secureUpi: "100% Secure UPI",
    qrVerificationTitle: "Hostel OS QR Verification",
    digitallyVerifiedReceipt: "DIGITALLY VERIFIED PAYMENT RECEIPT",
    enterDepositPlaceholder: "Enter deposit amount",
    enterAmountPlaceholder: "Enter amount",
    hawkEyeVerifiedRecord: "Cyberabad Police HawkEye Verified Record",

    // Payment Methods
    methodCash: "Cash",
    methodUpi: "UPI",
    methodSoundbox: "Soundbox"
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof Translations) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('hostel_os_lang');
    return (saved === 'te' || saved === 'hi' || saved === 'en') ? saved : 'te';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('hostel_os_lang', lang);
  };

  const t = (key: keyof Translations): string => {
    return translations[language]?.[key] || translations['en']?.[key] || String(key);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
